root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/rintik-auth"
  cmd = "swag init -g cmd/rintik-auth/main.go -o services/restapi/docs && go build -o ./tmp/rintik-auth ./cmd/rintik-auth"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "data_test", "badger", "services/restapi/docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./tmp/rintik-auth --log ./log/rintik-auth.log --config .configs.yml"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false